### ISSUE TITLE
Mute not working

### ISSUE THREAD

**Issue by tedlesmemes2** [turtlebasket/comrade-bot#6]
Ignoring exception in command mute:
Traceback (most recent call last):
  File "C:\Users\teddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "helppls.py", line 250, in mute
    await muted_role.edit(position=ctx.guild.get_member(target_user.id).top_role.position+1)
AttributeError: 'NoneType' object has no attribute 'top_role'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\teddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\teddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\teddy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'top_role'

**Comment by Nathanmarc** [comment]
same error

**Comment by tedlesmemes2** [comment]
Replace line 266-290 with this


 async def addrole(ctx):
                member = target_user
                role = get(member.server.roles, name="Muted")
                await bot.add_roles(member, role)

            # change channel permissions for new role
            for channel in ctx.guild.channels:
                if type(channel) is discord.TextChannel and target_user in channel.members:
                    await channel.set_permissions(muted_role, read_messages=True, send_messages=False,
                                                  add_reactions=False)

                elif type(channel) is discord.VoiceChannel:
                    await channel.set_permissions(muted_role, connect=False)

            # Give role to member
            from discord.ext import commands
            from discord.utils import get
            member = target_user
            role = get(member.guild.roles, name="Muted")
            await member.add_roles(discord.utils.get(member.guild.roles, name="Muted"))
            await ctx.send(
                "**{0}, the majority has ruled that you should be muted.** See ya in {1} minutes!".format(target_user,
                                                                                                          int(MUTE_TIME / 60)))
            await asyncio.sleep(MUTE_TIME)
            await muted_role.delete()
